/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface RequestData {
  deviceUniqueId: string;
  photoType: 'data' | 'thumbnail' | 'compressed' | 'original';
  photosData: {
    date: string;
    path: string;
    size: number;
  }[];
}
