/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface RequestData {
  number: number;
  offset: number;
  photoType: 'data' | 'thumbnail' | 'compressed' | 'original';
}
