const PHOTO_TYPE_DATA = "data";
const PHOTO_TYPE_THUMBNAIL = "thumbnail";
const PHOTO_TYPE_COMPRESSED = "compressed";
const PHOTO_TYPE_ORIGINAL = "original";

const PHOTO_TYPES = [
  PHOTO_TYPE_DATA,
  PHOTO_TYPE_THUMBNAIL,
  PHOTO_TYPE_COMPRESSED,
  PHOTO_TYPE_ORIGINAL,
];

export default {
  PHOTO_TYPE_DATA,
  PHOTO_TYPE_THUMBNAIL,
  PHOTO_TYPE_COMPRESSED,
  PHOTO_TYPE_ORIGINAL,
  PHOTO_TYPES,
};
