/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface RequestData {
  date: string;
  deviceUniqueId: string;
  fileSize: number;
  height: number;
  image64Len: number;
  name: string;
  path: string;
  width: number;
}
