export const endpointsPath = {
  addPhoto: "addPhoto",
  addPhotoInit: "addPhotoInit",
  addPhotoPart: "addPhotoPart",
  claimServer: "claimServer",
  deletePhotosById: "deletePhotosById",
  getLastWarning: "getLastWarning",
  getNumberPhotos: "getNumberPhotos",
  getPhotoPartById: "getPhotoPartById",
  getPhotos: "getPhotos",
  getPhotosById: "getPhotosById",
  getPhotosByPath: "getPhotosByPath",
  getServerInfo: "getServerInfo",
  getToken: "getToken",
  unclaimServer: "unclaimServer",
  updatePhotoPath: "updatePhotoPath",
  updateServerName: "updateServerName",
  updateServerPath: "updateServerPath",
  whoAmI: "whoAmI",
};
