export * as AddPhoto from './EndpointsApi/addPhoto';
export * as AddPhotoInit from './EndpointsApi/addPhotoInit';
export * as AddPhotoPart from './EndpointsApi/addPhotoPart';
export * as ClaimServer from './EndpointsApi/claimServer';
export * as DeletePhotosById from './EndpointsApi/deletePhotosById';
export * as GetLastWarning from './EndpointsApi/getLastWarning';
export * as GetNumberPhotos from './EndpointsApi/getNumberPhotos';
export * as GetPhotoPartById from './EndpointsApi/getPhotoPartById';
export * as GetPhotos from './EndpointsApi/getPhotos';
export * as GetPhotosById from './EndpointsApi/getPhotosById';
export * as GetPhotosByPath from './EndpointsApi/getPhotosByPath';
export * as GetServerInfo from './EndpointsApi/getServerInfo';
export * as GetToken from './EndpointsApi/getToken';
export * as UnclaimServer from './EndpointsApi/unclaimServer';
export * as UpdatePhotoPath from './EndpointsApi/updatePhotoPath';
export * as UpdateServerName from './EndpointsApi/updateServerName';
export * as UpdateServerPath from './EndpointsApi/updateServerPath';
export * as WhoAmI from './EndpointsApi/whoAmI';

export * from './Types';
