// IMPORTS
import dotenv from 'dotenv';
import SysTray, { ClickEvent } from 'forked-systray';
import { main } from './mainFunction';

dotenv.config();

main().catch(err => {
  console.log('error init server');
  console.log(err);
});

const systray: any = new SysTray({
  menu: {
    icon: 'AAABAAEAEBAAAAEACABoBQAAFgAAACgAAAAQAAAAIAAAAAEACAAAAAAAAAEAABMLAAATCwAAAAEAAAABAABJPQoAEBEHAH5nDQCeiRgAX1IQAHZmEwAREgcAt5MRAMyzIAByYxMAfWcNAKCMGgCdhxgAU0cNAMivIACilSIAcGARAGhZEQCjlSIANSwIAG5aDQB8Zg8AgGsQAIJsEQCDbhEAhG8SAIVwEwCCbxMAb14QAGNSDAB/aA8AiXEQAIx0EQCOdhIAj3gTAJB5FACRexQAknwVAJJ9FgCRfRYAjHkWAGNRDACCaw8AloIYAJKAGAAzKwgAfmgPAJiGGgCTghoAbFkNAIhwEACaiBsAmYgbAHplDwCLcw8Am4ocAH9qEACNdRAAnYwdAI52EQCejh4AgWwRAI94EQCfjx8Agm4SAJB5EgCgkR8Ag28SAJF7FAChkiAAgGwSAJF8FQCikyEAaVkPAJB7FgCilCEAopQhAIl2FQCVgRgAopQhAKKVIgChlCMAkH0XAJeEGQCZhxoAopQhAKKVIgCilSIAkX8ZAJiGGwCaiRwAnIsdAJ2NHgCejh4An5AfAKCSIAChkyEAopQhAKCTIwCMcxAAjXURAI53EgCPeBMAkHoUAJJ7FACTfRUAlH8WAJWAFwCWghgAi3MQAIxzDgCNdA4Aj3gSAJF7FACRexIAknwSAJSAFgCXgxkAmIUZAJB4FgCyoV0AsqJcAJaAHwCRehMAlH4YAK2dTgDCtnkAopAyAJaDFwCZhxoAmoQqAO/s3gD+/vwA08qhAJaBHQC7rm0A+PfwAP///wC8r2oAloMVAJmGGgCaiBsAm4ocAJyHLQDx7uEA+vn1ALSlXQDm4ckA///+AL6ybQCXhBYAnIsdAJ2ILgD+/fwAw7d8AO7q2QCYhhcAm4kcAJyLHACdjR0AnoovAP39/ADDuHwAv7NuAJiHFgCcjBwAno4eAJ2JLADw7N4AxLl8AO7r2QD+/v0AvbJqAL+1bgDY0aUArJ8/AJ6PHQCVgBoA18+oAMW6fgDv7NwA7+zbALGjTADt6tcAyL99AJ6PHACUfxUAopAzANXNogDo5MsAtadZANfQpQDg27gAtKdUAKGSKADc1q0A5OC/ALGlSACgkh4AlYEXAJaCFgCYhRsAnowmAJqIHACdjCIAno0hAJyLGwCikycAo5UnAKGSHwCXhBkAmIYZAJqJGwCcjB0An48fAKCRHwChkiAAnIocAJ2MHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBELWFlaW1xdXl9gYWIPEg0OUlNU1NnaptbX2FVWVw8MTU7S04HUjtWm1tfYT1BRSUrHyMnKy8zNzqbP0NFLTEZHuru8vb6/wMHCw8TFxkhDRLGyiYmztIm1treJuLlFQEGnqImhqaqJq6ytrq+wQj0+oJCJoaKbiZSjpJelpj8WO5iQiZmam4mUlZydnp88ODmPkImRkpOJlJWWjY6XOjU2goOEhYaHiImKi4yNjjcxMnd4eXp7fH1+f4B2gTM0LS5tbm9wZ3Fyc3RsdXYvMAopKmNkZWZnaGlqa2wrLAsGBx0eHyAhIiMkJSYnKAgJAAECExQVFhcYGRobHAMEBeADAADAAQAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAQAAwAMAAOAHAAA=',
    title: '',
    tooltip: 'Tips',
    items: [
      {
        title: 'Exit',
        tooltip: 'bb',
        checked: false,
        enabled: true,
      },
    ],
  },
});

systray.on('click', (a: ClickEvent) => {
  if (a.seq_id == 0) {
    systray.kill();
  }
});
